server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # La línea mágica que arregla el 404:
        try_files $uri $uri/ /index.html; 
    }
}